name: 'Upload to AMO'
description: 'Publishes an updated version of a Web Extension on addons.mozilla.org'
inputs:
  amo_jwt_iss:
    description: The JWT issuer (also refered to as the API key) from https://addons.mozilla.org/en-US/developers/addon/api/key/
    required: true
  amo_jwt_secret:
    description: The JWT secret from https://addons.mozilla.org/en-US/developers/addon/api/key/
    required: true
  addon_id:
    description: The numeric add-on ID, addon slug, or add-on GUID
    required: true
  addon_file:
    description: Path to the addon file relative to `$GITHUB_WORKSPACE`.
    required: true
  src_file:
    description: Path to the source archive relative to `$GITHUB_WORKSPACE`.
  release_notes:
    description: Release notes to use for the new version.
runs:
  using: node20
  main: dist/index.js
