name: 'push'
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 22
      - run: |
          pnpm install
          pnpm tsc --noEmit
